"""Add scientific_name to Plant model

Revision ID: 0a7f1bb615a3
Revises: 0d03e5d6004b
Create Date: 2026-06-20 13:40:02.779376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7f1bb615a3'
down_revision = '0d03e5d6004b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scientific_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('scientific_name')

    # ### end Alembic commands ###
