"""Add image_source_url to Plant model

Revision ID: 0d03e5d6004b
Revises: 62725bf13314
Create Date: 2026-06-20 13:17:24.503317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d03e5d6004b'
down_revision = '62725bf13314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('native_distribution')
        batch_op.drop_column('family')
        batch_op.drop_column('genus')
        batch_op.drop_column('wiki_summary')
        batch_op.drop_column('scientific_name')
        batch_op.drop_column('common_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('common_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('scientific_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('wiki_summary', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('genus', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('family', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('native_distribution', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
