"""Add new fields to Plant model

Revision ID: 62725bf13314
Revises: 
Create Date: 2026-06-19 13:17:06.549298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62725bf13314'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_source_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('common_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('scientific_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('family', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('genus', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('native_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('wiki_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('wiki_summary')
        batch_op.drop_column('native_distribution')
        batch_op.drop_column('genus')
        batch_op.drop_column('family')
        batch_op.drop_column('scientific_name')
        batch_op.drop_column('common_name')
        batch_op.drop_column('image_source_url')

    # ### end Alembic commands ###
